export const events = [
  {
    id: 1,
    title: "Understanding Accessibility",
    start: "2024-01-15T10:00:00",
    end: "2024-01-15T12:00:00",
    description: "A workshop that teaches the basics of accessibility.",
    location: "Online (Zoom)",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 2,
    title: "Inclusive Sports Day",
    start: "2024-02-10T10:00:00",
    end: "2024-02-10T15:00:00",
    description: "A sports event with activities adapted for everyone, focusing on inclusion.",
    location: "Community Sports Center, Ahmedabad",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 3,
    title: "Assistive Technology Training",
    start: "2024-03-20T14:00:00",
    end: "2024-03-20T16:00:00",
    description: "Hands-on training on using assistive technology.",
    location: "Community Center, Room 101, Rajkot/Online (Zoom)",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 4,
    title: "Inclusive Design Principles",
    start: "2024-04-05T10:00:00",
    end: "2024-04-05T12:00:00",
    description: "Learn how to incorporate inclusive design principles into your projects.",
    location: "Online (Webinar)",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 5,
    title: "Accessible Art Exhibition",
    start: "2024-05-12T11:00:00",
    end: "2024-05-12T18:00:00",
    description: "An art exhibition with tactile pieces designed for visually impaired visitors.",
    location: "City Art Gallery, Vadodara",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 6,
    title: "Job Search Strategies for Disabled Individuals",
    start: "2024-06-20T09:00:00",
    end: "2024-06-20T11:00:00",
    description: "Strategies for career advancement for individuals with disabilities.",
    location: "Online (Google Meet)",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 7,
    title: "Advocacy and Rights for the Physically Impaired",
    start: "2024-07-15T15:00:00",
    end: "2024-07-15T17:00:00",
    description: "A session on the rights of physically impaired individuals and how to advocate for them.",
    location: "Online (Zoom)",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 8,
    title: "Mental Health Awareness for People with Disabilities",
    start: "2024-08-08T10:00:00",
    end: "2024-08-08T12:00:00",
    description: "A session on mental health challenges and solutions for the disabled community.",
    location: "Online (Webinar)",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 9,
    title: "Guide Dog Awareness Workshop",
    start: "2024-09-20T10:00:00",
    end: "2024-09-20T12:00:00",
    description: "Learn about guide dogs and their role in supporting visually impaired individuals.",
    location: "Animal Shelter Center, Vadodara",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 10,
    title: "Creating Accessible Digital Content",
    start: "2024-10-20T11:00:00",
    end: "2024-10-20T13:00:00",
    description: "Workshop on creating websites and documents that are accessible to everyone.",
    location: "Online (Google Meet)",
    registrationLink: "/sanidhya/event/registration",
  },
  {
    id: 11,
    title: "World Disability Day Celebration",
    start: "2024-12-03T10:00:00",
    end: "2024-12-03T16:00:00",
    description: "Celebrate achievements and progress in disability inclusion.",
    location: "Community Hall, Rajkot",
    registrationLink: "https://sanidhya-official.netlify.app/sanidhya/event/registration",
  },
  {
    id: 12,
    title: "Virtual Reality Experience for the Visually Impaired",
    start: "2024-12-15T14:00:00",
    end: "2024-12-15T16:00:00",
    description: "Experience virtual reality designed for the visually impaired.",
    location: "Innovation Lab, Ahmedabad",
    registrationLink: "/sanidhya/event/registration",
  },
];
